In [2]:
import pandas as pd
# Load dataset
df = pd.read_csv("sales_data.csv")

In [3]:
# Display first 5 rows
df.head()

         Date     Product  Quantity  Price Customer_ID Region  Total_Sales
0  2024-01-01       Phone         7  37300     CUST001   East       261100
1  2024-01-02  Headphones         4  15406     CUST002  North        61624
2  2024-01-03       Phone         2  21746     CUST003   West        43492
3  2024-01-04  Headphones         1  30895     CUST004   East        30895
4  2024-01-05      Laptop         8  39835     CUST005  North       318680

In [4]:
# Check shape (rows, columns)
df.shape

(100, 7)

In [5]:
# Check column names
df.columns

Index(['Date', 'Product', 'Quantity', 'Price', 'Customer_ID', 'Region',
       'Total_Sales'],
      dtype='object')

In [6]:
df.dtypes

Date           object
Product        object
Quantity        int64
Price           int64
Customer_ID    object
Region         object
Total_Sales     int64
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         100 non-null    object
 1   Product      100 non-null    object
 2   Quantity     100 non-null    int64
 3   Price        100 non-null    int64
 4   Customer_ID  100 non-null    object
 5   Region       100 non-null    object
 6   Total_Sales  100 non-null    int64
dtypes: int64(3), object(4)
memory usage: 5.6+ KB

In [8]:
df.describe()

         Quantity         Price    Total_Sales
count  100.000000    100.000000     100.000000
mean     4.780000  25808.510000  123650.480000
std      2.588163  13917.630242  100161.085275
min      1.000000   1308.000000    6540.000000
25%      2.750000  14965.250000   39517.500000
50%      5.000000  24192.000000   97955.500000
75%      7.000000  38682.250000  175792.500000
max      9.000000  49930.000000  373932.000000

In [9]:
df.isnull().sum()

Date           0
Product        0
Quantity       0
Price          0
Customer_ID    0
Region         0
Total_Sales    0
dtype: int64

In [10]:
df.fillna(0, inplace=True)

In [11]:
df.duplicated().sum()

0

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
total_revenue = df['Total_Sales'].sum()
print(f"Total Revenue: ₹{total_revenue:,.2f}")

Total Revenue: ₹12,365,048.00

In [14]:
average_sales = df['Total_Sales'].mean()
print(f"Average Sales: ₹{average_sales:,.2f}")

Average Sales: ₹123,650.48

In [15]:
max_sales = df['Total_Sales'].max()
min_sales = df['Total_Sales'].min()

print(f"Highest Sale: ₹{max_sales}")
print(f"Lowest Sale: ₹{min_sales}")

Highest Sale: ₹373932
Lowest Sale: ₹6540

In [ ]:
best_product = df.groupby('Product')['Total_Sales'].sum().idxmax()
print("Best Selling Product:", best_product)